version: '3.8'

services:
  app:
    build: .
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql://postgres:anil@db:5432/appointment_db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anil
      - POSTGRES_DB=appointment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
