"""init schema

Revision ID: 1846593418b1
Revises: 11a79f2c969c
Create Date: 2025-09-20 21:41:10.624762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1846593418b1"
down_revision: Union[str, None] = "11a79f2c969c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments",
        "status",
        existing_type=postgresql.ENUM(
            "SCHEDULED", "COMPLETED", "CANCELLED", "PENDING", name="appointmentstatus"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "appointments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        "appointments_appointment_id_key", "appointments", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "appointments_appointment_id_key",
        "appointments",
        ["appointment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "appointments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "appointments",
        "status",
        existing_type=postgresql.ENUM(
            "SCHEDULED", "COMPLETED", "CANCELLED", "PENDING", name="appointmentstatus"
        ),
        server_default=sa.text("'SCHEDULED'::appointmentstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
