apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appointment-staging

resources:
  - namespace.yaml
  - postgres.yaml
  - service.yaml
  - deployment.yaml
  - secrets.yaml

images:
  - name: appointment-service
    newName: appointment-service
    newTag: latest