apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: appointment-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "appointment_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "anil"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}  # Data will be lost when pod restarts

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: appointment-staging
spec:
  selector:
    app: postgres
  ports:
  - port: 5432