apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: appointment-staging
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: appointment-service